version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  demo-controller:
    build: ./demo-controller
    ports:
      - "8080:8080"
